import type { Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Navber from "@/components/navber";
import Footer from "@/components/footer";
import Providers from "./providers";

import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
         
          <Providers>
            <Navber />
            {children}
            <Footer />
          </Providers>

        </body>
      </html>
    </ClerkProvider>
  );
}











